### ISSUE TITLE
ADD Basic Developer API 

### ISSUE THREAD

**Issue by ankit2001** [OWASP/SKF-VideoEditorAPI#2]
We need a token generation REST Endpoint(POST Request) for developer, you can say it as a sign up api, which will ask for organization, email, name, phone number and password from a developer and will create a token corresponding to that account. 
After that we need /signin or /verfication endpoint as well to authenticate the token.

**Comment by ankit2001** [comment]
Anyone wants to take this up? Shweta or Aryan?

**Comment by ankit2001** [comment]
Sure, assigned

**Comment by shwetagurnani** [comment]
Hi @ankit2001, I have done the changes but just want to know should I use local Mysql database for the apis changes? Or use sqlite one?

**Comment by ankit2001** [comment]
Hi @shwetagurnani, you can test on sqlite as well, on local if you are using django query
Thanks
