### ISSUE TITLE
ADD Github Actions and Workflow

### ISSUE THREAD

**Issue by ankit2001** [OWASP/SKF-VideoEditorAPI#4]
ADD DependaBot or Issue Assigner, more suggestions will be appreciated

**Comment by ankit2001** [comment]
Yes, we are looking for that. It would be really appreciate if you can contribute towared issue assigner or something.
Thanks

**Comment by 0x41head** [comment]
No, I was asking about what the assigner bot would do. Do we statically assign the same person to every single issue ?

**Comment by ankit2001** [comment]
If you write in the comment, assign to me.
Then the bot will assign you for 3 days. If you have not created the pr
till 3 days. It will unassign you. Do you have any more questions?

**Comment by 0x41head** [comment]
Let me write the timeline to ensure we are on the same page:

- Issue created
- Issue assigner assigns the issue to you
- Person A comments on issue
- Issue assigner assigns issue to person A and unassigns you
- If no PR made in 3 days. Issue unassigned from person A

Is my understanding correct ?

**Comment by ankit2001** [comment]
Yes correct. Thanks
You can start working on it.
